### ISSUE TITLE
Check or reproduce extraction

### ISSUE THREAD

**Issue by emillon** [mirage/fiat#4]
Hi,

`p256_{32,64}.h` are extracted from Coq. They are picked from <https://github.com/mit-plv/fiat-crypto/>, files `p256_{32,64}.c`. It would be great if users wouldn't have to trust our word on this 🙂.

Extraction is a bit expensive, so it might not be feasible to do it at every build, but an extra command to fetch a given hash from the upstream repository and promote the generated file would be useful.

Also, generated files should be in a different directory so that they do not get modified.

**Comment by NathanReb** [comment]
This was done in #24!
